# Generated by Django 5.2.11 on 2026-03-10 09:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('programme', models.CharField(blank=True, choices=[('BSCIT', 'Bachelor of Science in Information Technology'), ('BSCS', 'Bachelor of Science in Computer Science'), ('BBA', 'Bachelor of Business Administration'), ('BCOM', 'Bachelor of Commerce'), ('BED', 'Bachelor of Education'), ('BENG', 'Bachelor of Engineering'), ('BARCH', 'Bachelor of Architecture'), ('BLAW', 'Bachelor of Laws'), ('BMED', 'Bachelor of Medicine'), ('BNURS', 'Bachelor of Nursing'), ('BSC', 'Bachelor of Science'), ('BPHARM', 'Bachelor of Pharmacy'), ('BPSYCH', 'Bachelor of Psychology'), ('BSOC', 'Bachelor of Social Work'), ('BJOUR', 'Bachelor of Journalism')], max_length=20)),
                ('school', models.CharField(blank=True, choices=[('SET', 'School of Engineering & Technology'), ('SBS', 'School of Business Studies'), ('SEd', 'School of Education'), ('SHS', 'School of Health Sciences'), ('SLA', 'School of Law & Arts'), ('SSS', 'School of Social Sciences')], max_length=10)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('current_year', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')], default=1)),
                ('student_id', models.CharField(blank=True, max_length=30)),
                ('national_id', models.CharField(blank=True, max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('role', models.CharField(choices=[('student', 'Student'), ('iebc', 'IEBC Official'), ('admin', 'Admin')], default='student', max_length=20)),
                ('is_registered_voter', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('academic_year', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('voting_start', models.DateTimeField()),
                ('voting_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active / Voting Open'), ('closed', 'Closed'), ('results_out', 'Results Published')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elections_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('president', 'Student President'), ('deputy_president', 'Deputy President'), ('secretary_general', 'Secretary General'), ('finance_director', 'Finance Director'), ('governor', 'School Governor'), ('mca', 'Programme Director (MCA)'), ('senator', 'School Senator')], max_length=30)),
                ('school', models.CharField(blank=True, choices=[('SET', 'School of Engineering & Technology'), ('SBS', 'School of Business Studies'), ('SEd', 'School of Education'), ('SHS', 'School of Health Sciences'), ('SLA', 'School of Law & Arts'), ('SSS', 'School of Social Sciences')], help_text='Required for school-specific positions', max_length=10)),
                ('programme', models.CharField(blank=True, choices=[('BSCIT', 'Bachelor of Science in Information Technology'), ('BSCS', 'Bachelor of Science in Computer Science'), ('BBA', 'Bachelor of Business Administration'), ('BCOM', 'Bachelor of Commerce'), ('BED', 'Bachelor of Education'), ('BENG', 'Bachelor of Engineering'), ('BARCH', 'Bachelor of Architecture'), ('BLAW', 'Bachelor of Laws'), ('BMED', 'Bachelor of Medicine'), ('BNURS', 'Bachelor of Nursing'), ('BSC', 'Bachelor of Science'), ('BPHARM', 'Bachelor of Pharmacy'), ('BPSYCH', 'Bachelor of Psychology'), ('BSOC', 'Bachelor of Social Work'), ('BJOUR', 'Bachelor of Journalism')], help_text='Required for MCA (Programme Director)', max_length=20)),
                ('manifesto', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('is_approved', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('running_mate', models.OneToOneField(blank=True, help_text='Deputy President linked to President', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='running_mate_of', to='elections.candidate')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election')),
            ],
            options={
                'ordering': ['position', 'student__full_name'],
                'unique_together': {('election', 'student', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('election', 'Election Notice'), ('result', 'Result Announcement'), ('warning', 'Warning')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.election')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('president', 'Student President'), ('deputy_president', 'Deputy President'), ('secretary_general', 'Secretary General'), ('finance_director', 'Finance Director'), ('governor', 'School Governor'), ('mca', 'Programme Director (MCA)'), ('senator', 'School Senator')], max_length=30)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-voted_at'],
                'unique_together': {('election', 'voter', 'position')},
            },
        ),
        migrations.CreateModel(
            name='VoterRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id_number', models.CharField(max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_registrations', to='elections.election')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations_reviewed', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'election')},
            },
        ),
    ]
